language: node_js
node_js:
- '0.10'
services:
  - xvfb
sudo: required
before_install:
  - export DISPLAY=:99.0
install:
  - npm install
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
